### ISSUE TITLE
  Failed building wheel for json2xml

### ISSUE THREAD

**Issue by hemanthprodduturi** [vinitkumar/json2xml#31]
pip3 install json2xml

Collecting json2xml
  Downloading https://files.pythonhosted.org/packages/45/a6/65509927c74eff40f001e7ab3e830849545cc8f41cc6111f1bc11c282391/json2xml-2.2.0.tar.gz
Collecting dict2xml==1.5 (from json2xml)
  Downloading https://files.pythonhosted.org/packages/7e/c7/728fe5b79783b2c44af4381820dd6cbfddf7ee2a27b79023b623fe189357/dict2xml-1.5.tar.gz
Requirement already satisfied: six==1.11.0 in /home/hemanth/anaconda3/lib/python3.6/site-packages (from json2xml) (1.11.0)
Requirement already satisfied: requests==2.18.4 in /home/hemanth/anaconda3/lib/python3.6/site-packages (from json2xml) (2.18.4)
Collecting xmltodict==0.11.0 (from json2xml)
  Downloading https://files.pythonhosted.org/packages/42/a9/7e99652c6bc619d19d58cdd8c47560730eb5825d43a7e25db2e1d776ceb7/xmltodict-0.11.0-py2.py3-none-any.whl
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/hemanth/anaconda3/lib/python3.6/site-packages (from requests==2.18.4->json2xml) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /home/hemanth/anaconda3/lib/python3.6/site-packages (from requests==2.18.4->json2xml) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/hemanth/anaconda3/lib/python3.6/site-packages (from requests==2.18.4->json2xml) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in /home/hemanth/anaconda3/lib/python3.6/site-packages (from requests==2.18.4->json2xml) (2017.7.27.1)
Building wheels for collected packages: json2xml, dict2xml
  Running setup.py bdist_wheel for json2xml ... error
  Complete output from command /home/hemanth/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-sjea2obu/json2xml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-svy2m8ib --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/src
  copying src/json2xml.py -> build/lib/src
  copying src/__init__.py -> build/lib/src
  copying src/cli.py -> build/lib/src
  running egg_info
  writing json2xml.egg-info/PKG-INFO
  writing dependency_links to json2xml.egg-info/dependency_links.txt
  writing requirements to json2xml.egg-info/requires.txt
  writing top-level names to json2xml.egg-info/top_level.txt
  reading manifest file 'json2xml.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'json2xml.egg-info/SOURCES.txt'
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/src
  copying build/lib/src/json2xml.py -> build/bdist.linux-x86_64/wheel/src
  copying build/lib/src/__init__.py -> build/bdist.linux-x86_64/wheel/src
  copying build/lib/src/cli.py -> build/bdist.linux-x86_64/wheel/src
  running install_egg_info
  Copying json2xml.egg-info to build/bdist.linux-x86_64/wheel/json2xml-2.2.0-py3.6.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-sjea2obu/json2xml/setup.py", line 19, in <module>
      'xmltodict==0.11.0'
    File "/home/hemanth/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/home/hemanth/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/hemanth/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/hemanth/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/hemanth/anaconda3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 215, in run
      self.run_command('install')
    File "/home/hemanth/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/hemanth/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/hemanth/anaconda3/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
      return orig.install.run(self)
    File "/home/hemanth/anaconda3/lib/python3.6/distutils/command/install.py", line 557, in run
      self.run_command(cmd_name)
    File "/home/hemanth/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/hemanth/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/hemanth/anaconda3/lib/python3.6/site-packages/setuptools/command/install_scripts.py", line 17, in run
      import setuptools.command.easy_install as ei
    File "/home/hemanth/anaconda3/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 52, in <module>
      from setuptools.package_index import (
    File "/home/hemanth/anaconda3/lib/python3.6/site-packages/setuptools/package_index.py", line 31, in <module>
      from setuptools.wheel import Wheel
  ModuleNotFoundError: No module named 'setuptools.wheel'
  
  ----------------------------------------
  Failed building wheel for json2xml
  Running setup.py clean for json2xml
  Running setup.py bdist_wheel for dict2xml ... error
  Complete output from command /home/hemanth/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-sjea2obu/dict2xml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-i499ukwb --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/dict2xml
  copying dict2xml/logic.py -> build/lib/dict2xml
  copying dict2xml/__init__.py -> build/lib/dict2xml
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/dict2xml
  copying build/lib/dict2xml/logic.py -> build/bdist.linux-x86_64/wheel/dict2xml
  copying build/lib/dict2xml/__init__.py -> build/bdist.linux-x86_64/wheel/dict2xml
  running install_egg_info
  running egg_info
  writing dict2xml.egg-info/PKG-INFO
  writing dependency_links to dict2xml.egg-info/dependency_links.txt
  writing requirements to dict2xml.egg-info/requires.txt
  writing top-level names to dict2xml.egg-info/top_level.txt
  reading manifest file 'dict2xml.egg-info/SOURCES.txt'
  writing manifest file 'dict2xml.egg-info/SOURCES.txt'
  Copying dict2xml.egg-info to build/bdist.linux-x86_64/wheel/dict2xml-1.5-py3.6.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-sjea2obu/dict2xml/setup.py", line 25, in <module>
      , license = "WTFPL"
    File "/home/hemanth/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/home/hemanth/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/hemanth/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/hemanth/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/hemanth/anaconda3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 215, in run
      self.run_command('install')
    File "/home/hemanth/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/hemanth/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/hemanth/anaconda3/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
      return orig.install.run(self)
    File "/home/hemanth/anaconda3/lib/python3.6/distutils/command/install.py", line 557, in run
      self.run_command(cmd_name)
    File "/home/hemanth/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/hemanth/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/hemanth/anaconda3/lib/python3.6/site-packages/setuptools/command/install_scripts.py", line 17, in run
      import setuptools.command.easy_install as ei
    File "/home/hemanth/anaconda3/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 52, in <module>
      from setuptools.package_index import (
    File "/home/hemanth/anaconda3/lib/python3.6/site-packages/setuptools/package_index.py", line 31, in <module>
      from setuptools.wheel import Wheel
  ModuleNotFoundError: No module named 'setuptools.wheel'
  
  ----------------------------------------
  Failed building wheel for dict2xml
  Running setup.py clean for dict2xml
Failed to build json2xml dict2xml
Installing collected packages: dict2xml, xmltodict, json2xml
  Running setup.py install for dict2xml ... error
    Complete output from command /home/hemanth/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-sjea2obu/dict2xml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-rxc6csoh/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/dict2xml
    copying dict2xml/logic.py -> build/lib/dict2xml
    copying dict2xml/__init__.py -> build/lib/dict2xml
    running install_lib
    creating /home/hemanth/anaconda3/lib/python3.6/site-packages/dict2xml
    copying build/lib/dict2xml/logic.py -> /home/hemanth/anaconda3/lib/python3.6/site-packages/dict2xml
    copying build/lib/dict2xml/__init__.py -> /home/hemanth/anaconda3/lib/python3.6/site-packages/dict2xml
    byte-compiling /home/hemanth/anaconda3/lib/python3.6/site-packages/dict2xml/logic.py to logic.cpython-36.pyc
    byte-compiling /home/hemanth/anaconda3/lib/python3.6/site-packages/dict2xml/__init__.py to __init__.cpython-36.pyc
    running install_egg_info
    running egg_info
    writing dict2xml.egg-info/PKG-INFO
    writing dependency_links to dict2xml.egg-info/dependency_links.txt
    writing requirements to dict2xml.egg-info/requires.txt
    writing top-level names to dict2xml.egg-info/top_level.txt
    reading manifest file 'dict2xml.egg-info/SOURCES.txt'
    writing manifest file 'dict2xml.egg-info/SOURCES.txt'
    Copying dict2xml.egg-info to /home/hemanth/anaconda3/lib/python3.6/site-packages/dict2xml-1.5-py3.6.egg-info
    running install_scripts
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-sjea2obu/dict2xml/setup.py", line 25, in <module>
        , license = "WTFPL"
      File "/home/hemanth/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/home/hemanth/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/hemanth/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/hemanth/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/hemanth/anaconda3/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/hemanth/anaconda3/lib/python3.6/distutils/command/install.py", line 557, in run
        self.run_command(cmd_name)
      File "/home/hemanth/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/hemanth/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/hemanth/anaconda3/lib/python3.6/site-packages/setuptools/command/install_scripts.py", line 17, in run
        import setuptools.command.easy_install as ei
      File "/home/hemanth/anaconda3/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 52, in <module>
        from setuptools.package_index import (
      File "/home/hemanth/anaconda3/lib/python3.6/site-packages/setuptools/package_index.py", line 31, in <module>
        from setuptools.wheel import Wheel
    ModuleNotFoundError: No module named 'setuptools.wheel'
    
    ----------------------------------------
Command "/home/hemanth/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-sjea2obu/dict2xml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-rxc6csoh/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-sjea2obu/dict2xml/

**Comment by vinitkumar** [comment]
Hi @hemanthprodduturi, Looks like the issue is with your setuptools module
that comes with your anaconda installation and is also evident from the error

```sh
pip install --upgrade setuptools
```
Do this and try to run the command to install json2xml again and it should just work.

For reference, you can also see the similar crash reported in this Github issue. https://github.com/cuemacro/findatapy/issues/17

**Comment by vinitkumar** [comment]
Closing this issue as no response from the poster.
