### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by yfried-redhat** [vinitkumar/json2xml#5]
trying to install:
$ pip install -U json2xml  
Collecting json2xml
  Downloading json2xml-1.0.0.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-92CsKj/json2xml/setup.py", line 17, in <module>
        'requirements.txt')).read().split(),
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-92CsKj/json2xml/requirements.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-92CsKj/json2xml/setup.py", line 17, in <module>
    
        'requirements.txt')).read().split(),
    
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-92CsKj/json2xml/requirements.txt'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-92CsKj/json2xml

**Comment by vinitkumar** [comment]
I can confirm the bug. Will release a fix tonight.

**Comment by vinitkumar** [comment]
This is fixed. Use the latest pypi release.
