### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by jayvdb** [vinitkumar/json2xml#8]
```
$ sudo python3.4 setup.py install
running install
running bdist_egg
running egg_info
writing pbr to json2xml.egg-info/pbr.json
writing requirements to json2xml.egg-info/requires.txt
writing json2xml.egg-info/PKG-INFO
writing top-level names to json2xml.egg-info/top_level.txt
writing dependency_links to json2xml.egg-info/dependency_links.txt
reading manifest file 'json2xml.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'history.md'
writing manifest file 'json2xml.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/json2xml
copying build/lib/json2xml/json2xml.py -> build/bdist.linux-x86_64/egg/json2xml
copying build/lib/json2xml/__init__.py -> build/bdist.linux-x86_64/egg/json2xml
byte-compiling build/bdist.linux-x86_64/egg/json2xml/json2xml.py to json2xml.cpython-34.pyc
  File "build/bdist.linux-x86_64/egg/json2xml/json2xml.py", line 33
    print "I/O error({0}): {1}".format(e.errno, e.strerror)
                              ^
SyntaxError: invalid syntax
...
Processing dependencies for json2xml==1.0.1
Searching for wsgiref==0.1.2
Reading https://pypi.python.org/simple/wsgiref/
Best match: wsgiref 0.1.2
Downloading https://pypi.python.org/packages/source/w/wsgiref/wsgiref-0.1.2.zip#md5=29b146e6ebd0f9fb119fe321f7bcf6cb
Processing wsgiref-0.1.2.zip
Writing /tmp/easy_install-15t7k6i3/wsgiref-0.1.2/setup.cfg
Running wsgiref-0.1.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-15t7k6i3/wsgiref-0.1.2/egg-dist-tmp-3y_lk_nn
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 239, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 269, in run
    return func()
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 238, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-15t7k6i3/wsgiref-0.1.2/setup.py", line 5, in <module>
    
  File "/tmp/easy_install-15t7k6i3/wsgiref-0.1.2/ez_setup/__init__.py", line 170
    print "Setuptools version",version,"or greater has been installed."
                             ^
SyntaxError: Missing parentheses in call to 'print'
...
```

**Comment by vinitkumar** [comment]
@jayvdb Thanks for reporting the issue. I will try and release py3 compatible release soon.

**Comment by vinitkumar** [comment]
@jayvdb Python3 support is there. Feel free to test and let me know how it goes. :dancers:
